### ISSUE TITLE
bring in nib/stylus mix-ins to make some cuter features without too much sweating

### ISSUE THREAD

**Issue by bastienboutonnet** [alexisboutonnet/siteKirby#16]
# **Nib/Stylus**

## Installs
- install nodel.js (https://nodejs.org/en/download/)
- check shit works run the following command in terminal `node -v` (it should spit out a version number)
- install nib and stylus: `sudo npm install -g stylus nib`

## Implementation
- instead of writing .css straight away, we write `css` language and mix in `stylus/nib` language in a `.styl` page.
- we then **compile** that file using e.g., `stylus -u nib sheet.styl` from within the folder and it spits out a `.css` file with essentially a lot of painful code we would have had to write from scratch.
- ce qui est bien c'est que l'on écrit essentiellement du css, mais on le mixe avec des access aux raccourcis de stylus.
- the link rel in the header of the html/php file would be to the **compiled** `css` file of course and not the `styl`.

## Refs
- http://www.clock.co.uk/blog/compiling-css-using-stylus-getting-started
- https://www.sitepoint.com/getting-to-know-stylus/

**Comment by alexisboutonnet** [comment]
Stylus import succesfull

**Comment by alexisboutonnet** [comment]
Stylus import succesfull
